blank_issues_enabled: false
contact_links:
  - name: ğŸ“šDocumentation
    url: http://docs./* Replaced /* Replaced guzzle */ */php.org
    about: Check the documentation before opening an issue.

  - name: â“Support
    url: https://github.com//* Replaced /* Replaced guzzle */ *//.github/blob/master/.github/SUPPORT.md
    about: We use GitHub issues only to discuss bugs and new features.
